apiVersion: v1
kind: ConfigMap

metadata:
  name: pi-calculator
  labels:
    app.kubernetes.io/name: pi-calculator
    app.kubernetes.io/part-of: kubernetes-workshop
    app.kubernetes.io/kubernetes-component: ConfigMap

data:
  nginx.conf: |-
    # This is to make sure Nginx can run as an unprivileged user
    pid /tmp/nginx.pid;

    worker_processes auto;

    events {
        worker_connections  1024;
    }

    http {
        include       mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log /dev/stdout main;
        error_log /dev/stderr warn;

        # These are to make sure Nginx can run as an unprivileged user
        client_body_temp_path /tmp/nginx 1 2;
        proxy_temp_path /tmp/nginx-proxy;
        fastcgi_temp_path /tmp/nginx-fastcgi;
        uwsgi_temp_path /tmp/nginx-uwsgi;
        scgi_temp_path /tmp/nginx-scgi;

        server {
            listen   8080;
            listen   [::]:8080 default ipv6only=on;

            server_name _;

            location / {
                root   /var/www/html;
                index  index.html;
            }
        }
    }
