apiVersion: apps/v1
kind: Deployment

metadata:
  name: pi-calculator
  labels:
    app.kubernetes.io/name: pi-calculator
    app.kubernetes.io/part-of: kubernetes-workshop
    app.kubernetes.io/kubernetes-component: deployment

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pi-calculator
      app.kubernetes.io/part-of: kubernetes-workshop
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pi-calculator
        app.kubernetes.io/part-of: kubernetes-workshop
        app.kubernetes.io/kubernetes-component: pod
    spec:
      securityContext:
        runAsUser: 65534
      containers:
        - name: nginx
          image: nginx:1.19-alpine
          ports:
            - name: http
              containerPort: 8080
          startupProbe:
            httpGet:
              path: /health
              port: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          volumeMounts:
            - name: pi-calculator
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
          resources:
            requests:
              memory: 8Mi
              cpu: 10m
            limits:
              memory: 8Mi
              cpu: 10m
        - name: php
          image: pi-calculator:php-fpm
          imagePullPolicy: Never # Force Kubernetes to use local docker image
          startupProbe:
            tcpSocket:
              port: 9000
          readinessProbe:
            tcpSocket:
              port: 9000
          livenessProbe:
            tcpSocket:
              port: 9000
          resources:
            requests:
              memory: 16Mi
              cpu: 500m
            limits:
              memory: 16Mi
              cpu: 1000m
      volumes:
        - name: pi-calculator
          configMap:
            name: pi-calculator
